data/urls.py
from django.urls import path
from data import views

app_name = 'data'

urlpatterns = [
    path('article_list/', views.article_list, name='article_list'),
    path('article_detail/<int:pk>/', views.article_detail, name='article_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from data import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('data/', include('data.urls')),
]

data/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

data/views.py
from django.shortcuts import render
from data.models import Article
# Create your views here.

def index(request):
    return render(request, 'data/index.html')

def article_list(request):
    articles = Article.objects.all()
    return render(request, 'data/list.html', {'articles': articles})

def article_detail(request, pk):
    article = Article.objects.get(id=pk)
    return render(request, 'data/detail.html', {'article': article})

data/templates/data/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django Tutorial{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

data/templates/data/detail.html
{% extends 'data/base.html' %}
{% load static %}
{% block content %}
<div class="jumbotron">
    <h1><a href="{% url 'data:article_list' %}">{{ article.title }}</a></h1>
    <h5>Category:{{ article.category }}</h5>
    <p>{{ article.description }}</p>
</div>
{% endblock %}

data/templates/data/index.html
{% extends 'data/base.html' %}
{% load static %}
{% block content %}
<div class="jumbotron">
    <h1>Hello World</h1>
</div>
{% endblock %}

data/templates/data/list.html
{% extends 'data/base.html' %}
{% load static %}
{% block content %}
<div class="jumbotron">
    {% for article in articles %}
    <h2><a href="{% url 'data:article_detail' article.id %}">{{ article.title }}</a></h2>
    <h5>Category:{{ article.category }}</h5>
    <p>{{ article.description }}</p>
    {% endfor %}
</div>
{% endblock %}